<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtkdaex\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtkdaex/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNtkdaex.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNtkdaex\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNtkdaex\appProdProjectContainer([
    'container.build_hash' => 'Ntkdaex',
    'container.build_id' => '16df1cb8',
    'container.build_time' => 1661182615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNtkdaex');
