<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3mxkr69\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3mxkr69/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3mxkr69.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3mxkr69\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3mxkr69\appDevDebugProjectContainer([
    'container.build_hash' => '3mxkr69',
    'container.build_id' => '98db017e',
    'container.build_time' => 1661226889,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3mxkr69');
